#! /bin/sh

#----------------------------------------------------------------------------
# Project MD
# Copyright 2012 Javier Degirolmo
#
# This file is part of Project MD.
#
# Project MD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Project MD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Project MD.  If not, see <http://www.gnu.org/licenses/>.
#----------------------------------------------------------------------------

# If you have a free replacement for asm68k, replace this function
# Will replace asm68k with a different assembler whenever I get the chance
asm68k() {
   wine "./ASM68K.EXE" /o w+,op+,os+,ow+,oz+,oaq+,osq+,omq+ /p $1, $2
}

asm68k build.68k projmd.bin
